# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class ToDoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.tasks = channel.unary_stream(
        '/todo.ToDo/tasks',
        request_serializer=todo__pb2.AllRequest.SerializeToString,
        response_deserializer=todo__pb2.Feature.FromString,
        )
    self.tasksAll = channel.unary_stream(
        '/todo.ToDo/tasksAll',
        request_serializer=todo__pb2.AllRequest.SerializeToString,
        response_deserializer=todo__pb2.SingleResponse.FromString,
        )
    self.taskSingle = channel.unary_unary(
        '/todo.ToDo/taskSingle',
        request_serializer=todo__pb2.SingleRequest.SerializeToString,
        response_deserializer=todo__pb2.SingleResponse.FromString,
        )
    self.taskCreate = channel.unary_unary(
        '/todo.ToDo/taskCreate',
        request_serializer=todo__pb2.CreateRequest.SerializeToString,
        response_deserializer=todo__pb2.SingleResponse.FromString,
        )
    self.taskUpdate = channel.unary_unary(
        '/todo.ToDo/taskUpdate',
        request_serializer=todo__pb2.UpdateRequest.SerializeToString,
        response_deserializer=todo__pb2.SingleResponse.FromString,
        )
    self.taskDelete = channel.unary_unary(
        '/todo.ToDo/taskDelete',
        request_serializer=todo__pb2.SingleRequest.SerializeToString,
        response_deserializer=todo__pb2.DeleteResponse.FromString,
        )


class ToDoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def tasks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def tasksAll(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def taskSingle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def taskCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def taskUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def taskDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ToDoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'tasks': grpc.unary_stream_rpc_method_handler(
          servicer.tasks,
          request_deserializer=todo__pb2.AllRequest.FromString,
          response_serializer=todo__pb2.Feature.SerializeToString,
      ),
      'tasksAll': grpc.unary_stream_rpc_method_handler(
          servicer.tasksAll,
          request_deserializer=todo__pb2.AllRequest.FromString,
          response_serializer=todo__pb2.SingleResponse.SerializeToString,
      ),
      'taskSingle': grpc.unary_unary_rpc_method_handler(
          servicer.taskSingle,
          request_deserializer=todo__pb2.SingleRequest.FromString,
          response_serializer=todo__pb2.SingleResponse.SerializeToString,
      ),
      'taskCreate': grpc.unary_unary_rpc_method_handler(
          servicer.taskCreate,
          request_deserializer=todo__pb2.CreateRequest.FromString,
          response_serializer=todo__pb2.SingleResponse.SerializeToString,
      ),
      'taskUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.taskUpdate,
          request_deserializer=todo__pb2.UpdateRequest.FromString,
          response_serializer=todo__pb2.SingleResponse.SerializeToString,
      ),
      'taskDelete': grpc.unary_unary_rpc_method_handler(
          servicer.taskDelete,
          request_deserializer=todo__pb2.SingleRequest.FromString,
          response_serializer=todo__pb2.DeleteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.ToDo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
